// $("#content").css("color", "red");
// $('.wrapper').css('color', 'red');
// $('h1, h2').css('color', 'red');
// $('article h2').css('color', 'red');
// $('article').find('h2').css('color', 'red');
// $('h1 + p').css('color', 'red');
// $('*').css('color', 'red');
// $('article > p').css('color', 'red');
// $('article > *').css('color', 'red');
$('article > p').css('color', 'red');
